### ISSUE TITLE
documentation for app

### ISSUE THREAD

**Issue by Ooblah** [yawhide/Lol-personal-counters#21]

**Comment by yawhide** [comment]
I can’t stress enough how important it is to have both good documentation and a presentation for your entry. When it comes to documentation, it doesn’t matter if you discovered time travel, if no one can replicate your project it loses value. As for having a presentation, you’ve spent three weeks working on your “baby” and everyone else takes around 3 minutes to judge it. Spend a couple of minutes highlighting what makes your project special and why other people should care. You can’t assume everyone will know exactly what you did and how it’s amazing.

Over the last two API Challenges, we’ve noticed many projects that have accomplished some impressive feats. They’ve run into unique challenges and have found elegant solutions to overcome them, however it’s fairly common that the challenges developers encounter aren’t highlighted as part of their presentation. One of the goals for each API Challenge is to strengthen and empower the developer community as a whole. When you document your project, spend some time talking about the technologies you used, why you chose them, and lessons you learned when working on your submission. Even an incomplete project can offer valuable insight to developers that follow in your footsteps.

**Comment by yawhide** [comment]
document the installation and setup process well
